FROM maven:3.3-jdk-8
WORKDIR /usr/src/pd
COPY /productcatalogue /usr/src/pd/
RUN mvn clean install
EXPOSE 8020
CMD ["java","-Djava.security.egd=file:/dev/./urandom","-jar","./target/productcatalogue-0.0.1-SNAPSHOT.jar","server", "product-catalogue.yml"]

