FROM maven:3.3-jdk-8
WORKDIR /usr/src/sm
COPY /stockmanager /usr/src/sm/
RUN mvn clean install
EXPOSE 8030
CMD ["java","-Djava.security.egd=file:/dev/./urandom","-jar","./target/stockmanager-0.0.1-SNAPSHOT.jar","server"]

